### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by epoxa** [nnupoor/webpack4vue#8]
```
git clone git@github.com:nnupoor/webpack4vue.git
npm install
npm run dev
```
gives me the error:
```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/www/cordova/webpack4vue/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /www/cordova/webpack4vue/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/www/cordova/webpack4vue/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
My environment (reported by the npm run dev):
Linux 4.15.0-42-generic
node v8.10.0
npm  v3.5.2
code ELIFECYCLE
Debug log attached
[npm-debug.log](https://github.com/nnupoor/webpack4vue/files/2761170/npm-debug.log)

**Comment by RayVector** [comment]
+1

I have the same problem.
